---
- name: Sync gitlab secrets to ansible host
  hosts: gitlab_cluster
  gather_facts: no
  roles:
    - gitlab_find_primary
  tasks:
    - name: Copy primary host gitlab-secrets.json to ansible host
      ansible.builtin.fetch:
        src: /etc/gitlab/gitlab-secrets.json
        dest: "files/{{ gitlab_secrets }}"
        flat: true
      become: true
      when: 
        - is_primary is defined
        - is_primary is true
      
  
- name: Sync gitlab secrets to secondary gitlab hosts
  hosts: gitlab_cluster
  gather_facts: no
  become: true
  tasks:
    - name: Copy new gitlab-secrets.json to secondary hosts
      ansible.builtin.copy:
        src: "files/{{ gitlab_secrets }}"
        dest: "/etc/gitlab/gitlab-secrets.json"
        mode: '600'
        owner: root



