---
- name: Create/update services for running playbooks
  hosts: all
  gather_facts: no
  run_once: true
  tasks: 
    # Loops through services defined in group_vars/all.yml 
    - name: Schedule a playbook systemd service and timer 
      vars:
        service_playbook: "{{ item.value.playbook }}"
        service_name: "{{ item.key }}"
        systemd_calendar_entry: "{{ item.value.calendar_entry }}"
      ansible.builtin.include_role:
        name: playbook_service_timer
      loop: "{{ services_timers | dict2items }}"

